### ISSUE TITLE
预览的文件的url可以把问号去掉吗

### ISSUE THREAD

**Issue by zhbdesign** [cngege/KodNES#1]

**Comment by cngege** [comment]
不知道你说的是哪个URL， 双击游戏文件后打开的游戏窗口 在窗口上边缘右键在浏览器新窗口中中打开，在浏览器的地址栏里链接分两部分，后边的是编码地址，解码后是游戏文件直链（要登录KodBox才能访问）前面的是插件地址，其中的问号都是不能去掉的
