### ISSUE TITLE
大佬666，有文档啥的嘛，想整个模型预览插件的（就是官方的AutoCAD)

### ISSUE THREAD

**Issue by moshuying** [cngege/KodNES#3]

**Comment by cngege** [comment]
没有Kodbox的文档，做插件的话 一个可以参考别人的插件，比如在kodbox插件文件夹中的插件，再一个可以参考 KodExplorer 的开发文档，虽然不一样，但是可以和其他人的插件对比着看。[KodExplorer开发文档](http://doc.kodcloud.com/#/plugins/main)
