### ISSUE TITLE
可以适配一下KodExplorer吗

### ISSUE THREAD

**Issue by CoolLoong** [cngege/KodNES#4]

**Comment by cngege** [comment]
KodExplorer 有KodExplorer版的模拟器 [https://bbs.kodcloud.com/d/76](https://bbs.kodcloud.com/d/76)

**Comment by CoolLoong** [comment]
> KodExplorer 有KodExplorer版的模拟器 https://bbs.kodcloud.com/d/76

这个插件我也在用，感觉没有你这个KOD版本好用。首先他不能改键，而且也没适配2P模式，手机端也没适配

**Comment by cngege** [comment]
抱歉 近期还没有KodExplorer的适配计划，因为我已经没有在使用KodExplorer了。后期不排除会适配KodExplorer的可能性（除非两个插件不兼容）
